export const data =[
    {
        id:1,
       thumbnail:"https://imgbb.su/images/2023/04/09/Presentacion-Narrada-Alquiler-Coches-Profesional-Azul-Purpura-1a48f23e86c3e3c12.png",
       title:"Inglés en la oficina: frases para sonar más profesional",
       subtitle:"A Beginner's Guide to Navigating the Supermarket Aisles",
       enlaceblog:"/PhrasesAtWork",
       channel:"sdasd",
       description:"¿Usas el inglés en la oficina? ¡No te pierdas nuestras frases en inglés para el trabajo! Si...",
    },
    {
        id:2,
       thumbnail:"https://i.ibb.co/N9jrwtn/Presentaci-n-Narrada-Alquiler-Coches-Profesional-Azul-P-rpura-2.png",
       title:"Inglés como un nativo con 50 frases de uso diario",
       subtitle:"A Beginner's Guide to Navigating the Supermarket Aisles",
       enlaceblog:"/PhrasesNative",
       channel:"sdasd",
       description:"Hello there super-motivated English student! En esta clase vamos a entrenar a fondo para que...",
    },
    {
        id:3,
       thumbnail:"https://i.ibb.co/k50xSzp/Presentaci-n-Narrada-Alquiler-Coches-Profesional-Azul-P-rpura-3.png",
       title:"No cometas estos errores en el examen B2 First",
       subtitle:"A Beginner's Guide to Navigating the Supermarket Aisles",
       enlaceblog:"/ErroresB2",
       channel:"sdasd",
       description:"¿Te presentas al examen B2 First? ¡No cometas los errores más comunes! En esta clase, revelaremos...",
    },
    {
        id:4,
       thumbnail:"https://images.pexels.com/photos/1181605/pexels-photo-1181605.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"Great Answers to 8 Common English Job Interview Questions",
       subtitle:"Here are 8 questions that they will likely ask, along with answers to help you rock (do well on) your interview.",
       enlaceblog:"/Interviewquestions",
       channel:"sdasd",
       description:"Searching for jobs is extremely stressful, but you know what’s even more stressful? ...",
    },
    {
        id:5,
       thumbnail:"https://images.pexels.com/photos/6347912/pexels-photo-6347912.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"B1 Preliminary",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/Preliminary",
       channel:"sdasd",
       description:"⚡️ El examen B1 Preliminary de Cambridge es algo distinto a partir de 2020. ...",
    },
    {
        id:6,
       thumbnail:"https://i.ibb.co/G9z8s8f/Presentaci-n-Narrada-Alquiler-Coches-Profesional-Azul-P-rpura-6.png",
       title:"Quiz! 10 errores muy comunes en inglés",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/Errores10",
       channel:"sdasd",
       description:"Hello there! ¿Tú también estás cometiendo estos 10 errores muy comunes en inglés? Esperamos",
    },
    {
        id:7,
       thumbnail:"https://i.ibb.co/VLpgwWm/Presentaci-n-Narrada-Alquiler-Coches-Profesional-Azul-P-rpura-5.png",
       title:"Opps! 5 errores gramaticales en inglés que puedes estar cometiendo",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/Mistakes5",
       channel:"sdasd",
       description:"Hello there! ¿Tú también estás cometiendo estos 10 errores muy comunes en inglés? Esperamos",
    }
    ,
    {
        id:8,
       thumbnail:"https://i.ibb.co/0GmTb4M/Presentaci-n-Narrada-Alquiler-Coches-Profesional-Azul-P-rpura-7.png",
       title:"Las palabras más confusas en inglés",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/ConfusingWords",
       channel:"sdasd",
       description:"Hello there! ¿Tú también estás cometiendo estos 10 errores muy comunes en inglés? Esperamos",
    } ,
    {
        id:9,
       thumbnail:"https://images.pexels.com/photos/207582/pexels-photo-207582.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"La diferencia entre ‘especially’ y ‘specially’",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/Specially",
       channel:"sdasd",
       description:"Hello there! ¿Tú también estás cometiendo estos 10 errores muy comunes en inglés? Esperamos",
    },
    {
        id:10,
       thumbnail:"https://images.pexels.com/photos/7092613/pexels-photo-7092613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"¿Tú también hablas inglés así? 5 errores muy comunes",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/ErroresComunes",
       channel:"sdasd",
       description:"¡Hoy toca un poquito de gramática inglesa! ¿Estarás tú también cometiendo estos 5 errores tan comunes en inglés?",
    },
    {
        id:11,
       thumbnail:"https://images.pexels.com/photos/7092613/pexels-photo-7092613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"¿Nivel avanzado de inglés?",
       subtitle:"¡Compruébalo con este test de gramática inglesa!",
       enlaceblog:"/AvanzadoEnIngles",
       channel:"sdasd",
       description:"Hello there student! Es hora de comprobar cómo de bien conoces la gramática inglesa y si tu nivel de inglés es tan avanzado como pones en tu curriculum. 🙈",
    }
]