export const data =[
    {
        id:1,
       thumbnail:"https://imgbb.su/images/2023/04/09/Presentacion-Narrada-Alquiler-Coches-Profesional-Azul-Purpura-1a48f23e86c3e3c12.png",
       title:"Inglés en la oficina: frases para sonar más profesional",
       subtitle:"A Beginner's Guide to Navigating the Supermarket Aisles",
       enlaceblog:"/PhrasesAtWork",
       channel:"sdasd",
       description:"¿Usas el inglés en la oficina? ¡No te pierdas nuestras frases en inglés para el trabajo! Si...",
    },
    {
        id:2,
       thumbnail:"https://i.ibb.co/N9jrwtn/Presentaci-n-Narrada-Alquiler-Coches-Profesional-Azul-P-rpura-2.png",
       title:"Inglés como un nativo con 50 frases de uso diario",
       subtitle:"A Beginner's Guide to Navigating the Supermarket Aisles",
       enlaceblog:"/PhrasesNative",
       channel:"sdasd",
       description:"Hello there super-motivated English student! En esta clase vamos a entrenar a fondo para que...",
    },
    {
        id:3,
       thumbnail:"https://i.ibb.co/k50xSzp/Presentaci-n-Narrada-Alquiler-Coches-Profesional-Azul-P-rpura-3.png",
       title:"No cometas estos errores en el examen B2 First",
       subtitle:"A Beginner's Guide to Navigating the Supermarket Aisles",
       enlaceblog:"/ErroresB2",
       channel:"sdasd",
       description:"¿Te presentas al examen B2 First? ¡No cometas los errores más comunes! En esta clase, revelaremos...",
    },
    {
        id:4,
       thumbnail:"https://images.pexels.com/photos/1181605/pexels-photo-1181605.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"Great Answers to 8 Common English Job Interview Questions",
       subtitle:"Here are 8 questions that they will likely ask, along with answers to help you rock (do well on) your interview.",
       enlaceblog:"/Interviewquestions",
       channel:"sdasd",
       description:"Searching for jobs is extremely stressful, but you know what’s even more stressful? ...",
    },
    {
        id:5,
       thumbnail:"https://images.pexels.com/photos/6347912/pexels-photo-6347912.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"B1 Preliminary",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/Preliminary",
       channel:"sdasd",
       description:"⚡️ El examen B1 Preliminary de Cambridge es algo distinto a partir de 2020. ...",
    },
    {
        id:6,
       thumbnail:"https://i.ibb.co/G9z8s8f/Presentaci-n-Narrada-Alquiler-Coches-Profesional-Azul-P-rpura-6.png",
       title:"Quiz! 10 errores muy comunes en inglés",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/Errores10",
       channel:"sdasd",
       description:"Hello there! ¿Tú también estás cometiendo estos 10 errores muy comunes en inglés? Esperamos",
    },
    {
        id:7,
       thumbnail:"https://i.ibb.co/VLpgwWm/Presentaci-n-Narrada-Alquiler-Coches-Profesional-Azul-P-rpura-5.png",
       title:"Opps! 5 errores gramaticales en inglés que puedes estar cometiendo",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/Mistakes5",
       channel:"sdasd",
       description:"Hello there! ¿Tú también estás cometiendo estos 10 errores muy comunes en inglés? Esperamos",
    }
    ,
    {
        id:8,
       thumbnail:"https://images.pexels.com/photos/4473496/pexels-photo-4473496.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"Las palabras más confusas en inglés que todos odiamos per oqu enecesitamos",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/ConfusingWords",
       channel:"sdasd",
       description:"Hello there! ¿Tú también estás cometiendo estos 10 errores muy comunes en inglés? Esperamos",
    } ,
    {
        id:9,
       thumbnail:"https://images.pexels.com/photos/207582/pexels-photo-207582.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"La diferencia entre ‘especially’ y ‘specially’",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/Specially",
       channel:"sdasd",
       description:"Hello there! ¿Tú también estás cometiendo estos 10 errores muy comunes en inglés? Esperamos",
    },
    {
        id:10,
       thumbnail:"https://images.pexels.com/photos/7092613/pexels-photo-7092613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"¿Tú también hablas inglés así? 5 errores muy comunes",
       subtitle:"Cambrdige Exam",
       enlaceblog:"/ErroresComunes",
       channel:"sdasd",
       description:"¡Hoy toca un poquito de gramática inglesa! ¿Estarás tú también cometiendo estos 5 errores tan comunes en inglés?",
    },
    {
        id:11,
       thumbnail:"https://images.pexels.com/photos/7092613/pexels-photo-7092613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"¿Nivel avanzado de inglés?",
       subtitle:"¡Compruébalo con este test de gramática inglesa!",
       enlaceblog:"/AvanzadoEnIngles",
       channel:"sdasd",
       description:"Hello there student! Es hora de comprobar cómo de bien conoces la gramática inglesa y si tu nivel de inglés es tan avanzado como pones en tu curriculum. 🙈",
    }
    ,
    {
        id:12,
       thumbnail:"https://www.logile.com/wp-content/uploads/2022/01/measuring-cashier-performance.jpg",
       title:"How to Stay Calm When the Cashier Asks You Quick Questions in English",
       subtitle:"¡Compruébalo con este test de gramática inglesa!",
       enlaceblog:"/StayCalmCashier",
       channel:"sdasd",
       description:"Hello there student! Es hora de comprobar cómo de bien conoces la gramática inglesa y si tu nivel de inglés es tan avanzado como pones en tu curriculum. 🙈",
    }
    ,
    {
        id:13,
       thumbnail:"https://www.logile.com/wp-content/uploads/2022/01/measuring-cashier-performance.jpg",
       title:"Love surprises?",
       subtitle:"We never know what’s coming up next in a conversation! ",
       enlaceblog:"/Surprise",
       channel:"sdasd",
       description:"With each photo you will find: a video description, highlighted vocabulary, and discussion questions for groups",
    },
    {
        id:14,
       thumbnail:"https://images.pexels.com/photos/8790977/pexels-photo-8790977.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"Dealing With Complaints for Customer Service Reps ",
       subtitle:"We never know what’s coming up next in a conversation! ",
       enlaceblog:"/DealingComplaints",
       channel:"sdasd",
       description:"W Mistakes happen. When they do, customer service representatives often need to handle consumers' complaints.",
    }
    ,
    {
        id:15,
       thumbnail:"https://images.pexels.com/photos/3719037/pexels-photo-3719037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"40 Common English Idioms ",
       subtitle:"We never know what’s coming up next in a conversation! ",
       enlaceblog:"/CommonIdioms",
       channel:"sdasd",
       description:"Learning English isn’t as easy as some might think.",
    },
    {
        id:16,
       thumbnail:"https://images.pexels.com/photos/3719037/pexels-photo-3719037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"Los verbos modales shall y should en inglés",
       subtitle:"We never know what’s coming up next in a conversation! ",
       enlaceblog:"/ShallShould",
       channel:"sdasd",
       description:"¿Llevas siglos en un sin vivir porque no consigues entender la diferencia entre shall y should en inglés? ",
    },
    {
        id:17,
       thumbnail:"https://images.pexels.com/photos/3719037/pexels-photo-3719037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"Verbos modales en inglés",
       subtitle:"We never know what’s coming up next in a conversation! ",
       enlaceblog:"/ModalVerbs",
       channel:"sdasd",
       description:"¿Llevas siglos en un sin vivir porque no consigues entender la diferencia entre shall y should en inglés? ",
    },
    {
        id:18,
       thumbnail:"https://i.ibb.co/xS904Cc/Abbreviations-1-760x400.png",
       title:"The 5 Types of Abbreviations",
       subtitle:"An abbreviation is a shortened form of a word or words ",
       enlaceblog:"/Abbreviations",
       channel:"sdasd",
       description:"¿Llevas siglos en un sin vivir porque no consigues entender la diferencia entre shall y should en inglés? ",
    },
    {
        id:19,
       thumbnail:"https://i.ibb.co/Smqy71q/Each-and-Every-760x405.jpg",
       title:"Each and Every: What’s the Difference?",
       subtitle:"An abbreviation is a shortened form of a word or words ",
       enlaceblog:"/EachEvery",
       channel:"sdasd",
       description:"¿Llevas siglos en un sin vivir porque no consigues entender la diferencia entre shall y should en inglés? ",
    },
    {
        id:20,
       thumbnail:"https://i.ibb.co/2PWvksh/Where-vs-In-which-vs-Wherein1-760x400.png",
       title:"Where vs. In Which vs. Wherein",
       subtitle:"An abbreviation is a shortened form of a word or words ",
       enlaceblog:"/WhereInWhichWherein",
       channel:"sdasd",
       description:"¿Llevas siglos en un sin vivir porque no consigues entender la diferencia entre shall y should en inglés? ",
    },
    {
        id:21,
       thumbnail:"https://i.ibb.co/2PWvksh/Where-vs-In-which-vs-Wherein1-760x400.png",
       title:"ARTICLES: THEY 1 FINALLY MAKE SENSE",
       subtitle:"An abbreviation is a shortened form of a word or words ",
       enlaceblog:"/Article",
       channel:"sdasd",
       description:"¿Llevas siglos en un sin vivir porque no consigues entender la diferencia entre shall y should en inglés? ",
    },
    {
        id:22,
       thumbnail:"https://images.pexels.com/photos/3491678/pexels-photo-3491678.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"Los ‘Falsos Amigos’ del inglés («False Friends»)",
       subtitle:"An abbreviation is a shortened form of a word or words ",
       enlaceblog:"/FalseFriends",
       channel:"sdasd",
       description:"¿Llevas siglos en un sin vivir porque no consigues entender la diferencia entre shall y should en inglés? ",
    },
    {
        id:23,
       thumbnail:"https://images.pexels.com/photos/256417/pexels-photo-256417.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"-Holic, -Oholic, and -Aholic – Suffix, Meaning & Exampl",
       subtitle:"The -Aholic and -Oholic Suffixes",
       enlaceblog:"/SuffixinEnglish01",
       channel:"sdasd",
       description:"When it comes -aholic, -oholic, and -holic meanings, just remember that the actual suffix is -holic, and -aholic or -oholic are used phonetically",
    },
    {
        id:24,
       thumbnail:"https://images.pexels.com/photos/256417/pexels-photo-256417.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
       title:"-able and -ible",
       subtitle:"The suffixes -able and -ible both mean capable of or suitable for",
       enlaceblog:"/SuffixinEnglish02",
       channel:"sdasd",
       description:"The suffixes -able and -ible both mean capable of or suitable for",
    }
]