export const products = [
    {
      id: 1,
      thumbnail: "https://i.ibb.co/MkVH9Xhf/Chat-GPT-Image-3-abr-2025-13-26-52.png",
      title: "Ruta Autónoma A1",
      subtitle: "85 HORAS",
      dateAdded: "2025-04-02",
      calificacion: "Most Popular",
      description: "¡Tu primer paso en inglés! Aprende saludos, frases básicas y vocabulario esencial para presentarte y hablar del día a día.",
      enlaces: "https://learnibox.vercel.app/RoadMapA1",
      precio: 35,
      demo: "AAS"
    },
    {
      id: 2,
      thumbnail: "https://i.ibb.co/SXmGyP1x/Chat-GPT-Image-3-abr-2025-13-29-31.png",
      title: "Ruta A2",
      subtitle: "English",
      dateAdded: "2025-04-02",
      calificacion: "Most Popular",
      description: "Mejora tu base de inglés: empieza a formar frases completas, hablar de rutinas, lugares y actividades cotidianas.",
      enlaces: "https://learnibox.vercel.app/RoadMap",
      precio: 35,
      demo: "AAS"
    },
    {
      id: 3,
      title: "Ruta B1",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/WN4Cg1cd/Chat-GPT-Image-3-abr-2025-13-31-27.png",
      dateAdded: "2025-04-02",
      calificacion: "Most Popular",
      description: "¡Hora de expresarte! Aprende a dar opiniones, hablar en pasado y entender conversaciones sencillas.",
      enlaces: "https://learnibox.vercel.app/RoadMapB1",
      precio: 35,
      demo: "AAS"
    },
    {
      id: 4,
      title: "Ruta B2",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/20d7Xr7D/Chat-GPT-Image-3-abr-2025-13-41-36.png",
      dateAdded: "2025-04-02",
      calificacion: "Most Popular",
      description: "Domina estructuras más complejas, conéctate con hablantes nativos y prepárate para situaciones reales.",
      enlaces: "https://learnibox.vercel.app/RoadMapB2",
      precio: 40,
      demo: "AAS"
    },
    {
      id: 5,
      title: "Ruta C1",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/21wD37dC/Chat-GPT-Image-3-abr-2025-13-36-49.png",
      dateAdded: "2025-04-02",
      calificacion: "Most Popular",
      description: "Habla con fluidez, defiende tus ideas con claridad y entiende textos y audios avanzados.",
      enlaces: "https://learnibox.vercel.app/RoadMapC1",
      precio: 45,
      demo: "AAS"
    },
    {
      id: 6,
      title: "Ruta C2",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/9kdyKGk1/Chat-GPT-Image-3-abr-2025-13-39-53.png",
      dateAdded: "2025-04-02",
      calificacion: "Most Popular",
      description: "Nivel experto: domina el inglés con precisión, como un hablante nativo en entornos académicos y profesionales.",
      enlaces: "https://learnibox.vercel.app/myenglishbro",
      precio: 50,
      demo: "AAS"
    },
    {
      id: 7,
      title: "Cambridge B2 First",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/wNmDwJVX/Chat-GPT-Image-3-abr-2025-11-59-43.png",
      dateAdded: "2025-04-02",
      calificacion: "Gratis",
      description: "Prepárate para aprobar el B2 First (FCE) con estrategias, práctica de speaking, writing y mucho más.",
      enlaces: "https://learnibox.vercel.app/myenglishbro",
      precio: 0,
      demo: "AAS"
    },
    {
      id: 8,
      title: "Cambridge C1 Advanced",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/HpKxMN1W/Chat-GPT-Image-3-abr-2025-13-09-48.png",
      dateAdded: "2025-04-02",
      calificacion: "Gratis",
      description: "Supera el C1 Advanced (CAE) con ejercicios tipo examen y simulacros reales.",
      enlaces: "https://learnibox.vercel.app/myenglishbro",
      precio: 0,
      demo: "AAS"
    },
    
    {
      id: 10,
      title: "IELTS Preparation",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/wN520qnQ/Chat-GPT-Image-3-abr-2025-13-52-46.png",
      dateAdded: "2025-04-02",
      calificacion: "Gratis",
      description: "Entrena todas las habilidades (Listening, Reading, Writing, Speaking) para tu mejor score en el IELTS.",
      enlaces: "https://learnibox.vercel.app/myenglishbro",
      precio: 0,
      demo: "AAS"
    },
    {
      id: 11,
      title: "CELPIP Speaking",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/tMhCmrgZ/Chat-GPT-Image-3-abr-2025-11-55-42.png",
      dateAdded: "2025-04-02",
      calificacion: "Gratis",
      description: "Aprende a dominar el examen canadiense CELPIP con plantillas, estrategias y práctica guiada.",
      enlaces: "https://learnibox.vercel.app/myenglishbro",
      precio: 0,
      demo: "AAS"
    },
    {
      id: 12,
      title: "Inglés para negocios",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/FbTL6wJQ/Chat-GPT-Image-3-abr-2025-11-03-01.png",
      dateAdded: "2025-04-02",
      calificacion: "Gratis",
      description: "Aprende inglés para reuniones, presentaciones, correos y negociaciones internacionales.",
      enlaces: "https://learnibox.vercel.app/RoadMapBusiness",
      precio: 0,
      demo: "AAS"
    },
    {
      id: 13,
      title: "Inglés para IT",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/8gj3GF41/Chat-GPT-Image-3-abr-2025-11-00-15.png",
      dateAdded: "2025-04-02",
      calificacion: "Gratis",
      description: "Habla de código, frameworks y proyectos en inglés técnico con confianza.",
      enlaces: "https://learnibox.vercel.app/myenglishbro",
      precio: 0,
      demo: "AAS"
    },
    {
      id: 14,
      title: "Inglés para médicos",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/qYLnBVSf/Chat-GPT-Image-3-abr-2025-11-04-57.png",
      dateAdded: "2025-04-02",
      calificacion: "Gratis",
      description: "Comunícate con pacientes y colegas en inglés clínico y profesional.",
      enlaces: "https://learnibox.vercel.app/myenglishbro",
      precio: 0,
      demo: "AAS"
    },
    {
      id: 17,
      title: "Inglés para Abogados",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/S4b3kDYc/Chat-GPT-Image-3-abr-2025-12-09-39.png",
      dateAdded: "2025-04-02",
      calificacion: "Gratis",
      description: "Domina el inglés en reclutamiento, entrevistas, onboarding y más en Recursos Humanos.",
      enlaces: "https://learnibox.vercel.app/myenglishbro",
      precio: 10,
      demo: "AAS"
    },
    {
      id: 15,
      title: "Inglés para Cocineros",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/4R202s1T/Chat-GPT-Image-3-abr-2025-11-27-03.png",
      dateAdded: "2025-04-02",
      calificacion: "Gratis",
      description: "Domina el inglés en reclutamiento, entrevistas, onboarding y más en Recursos Humanos.",
      enlaces: "https://learnibox.vercel.app/myenglishbro",
      precio: 10,
      demo: "AAS"
    },
   
    {
      id: 16,
      title: "Inglés para Banqueros",
      subtitle: "English",
      thumbnail: "https://i.ibb.co/gLm5hFdb/Chat-GPT-Image-3-abr-2025-11-52-24.png",
      dateAdded: "2025-04-02",
      calificacion: "Gratis",
      description: "Domina el inglés en reclutamiento, entrevistas, onboarding y más en Recursos Humanos.",
      enlaces: "https://learnibox.vercel.app/myenglishbro",
      precio: 10,
      demo: "AAS"
    },
 
  ]
  